SHELL := /bin/bash
PROJECT=rum
GOPATH ?= $(shell go env GOPATH)

# Ensure GOPATH is set before running build process.
ifeq "$(GOPATH)" ""
  $(error Please set the environment variable GOPATH before running `make`)
endif


GO                  := GO111MODULE=on go
GOBUILD             := $(GO) build $(BUILD_FLAG) -tags codes
GOTEST              := $(GO) test -v --count=1 --parallel=1 -p=


tree:
$(GOTEST) ./tree_test.go -run 1
$(GOTEST) ./routergroup_test.go -run 1
$(GOTEST) ./middleware_test.go -run 1
$(GOTEST) ./binding/binding_test -run 1
$(GOTEST) ./context_test.go -run 1